[package]
name = "fino"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.4.1"
clap = { version = "4.5.11", features = ["derive"] }
ena = "0.14.3"
im = "15.1.0"
logos = "0.14.0"
walkdir = "2.5.0"
