[package]
name = "fino"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.5.1"
clap = { version = "4.5.41", features = ["derive"] }
ena = "0.14.3"
im = "15.1.0"
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
logos = "0.15.0"
unescape = "0.1.0"
walkdir = "2.5.0"
